name: Generate Docs
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.7
      
      - name: Setup
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: docs
          folder: docs
